# - name: Converts Markdown to HTML
#   uses: jaywcjlove/markdown-to-html-cli@main
#   with:
#     source: README-zh.md
#     output: coverage/action.html
#     github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
#     favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>ğŸŒ</text></svg>